#!/bin/sh

APP=ysarys
CC=cc
CFLAGS=$(cat compile_flags.txt)
LDFLAGS=-lsqlite3
SRC_DIR=src
OBJ_DIR=.o.d
APP_DIR=dist

run() { echo "$@"; command $@; }
cc() { run "$CC" $@; }

mkdir -p "$OBJ_DIR"
for src in "$SRC_DIR"/*.c; do
  c="${src#src/}"
  o="${c%.c}.o"
  cc $CFLAGS -c "$src" -o "$OBJ_DIR/$o"
done

mkdir -p "$APP_DIR"
cc "$OBJ_DIR"/*.o $LDFLAGS -o "$APP_DIR/$APP"
