#!/bin/sh

. "${0%/*}/.env"

mkdir -p "$LIB_OBJ_DIR"
for src in "$LIB_SRC_DIR"/*.c; do
  c="${src#$LIB_SRC_DIR/}"
  o="${c%.c}.o"
  cc $CFLAGS -c "$src" -o "$LIB_OBJ_DIR/$o" || exit 1
done

mkdir -p "$APP_DIST_DIR"
for src in "$APP_SRC_DIR"/*.c; do
  c="${src#$APP_SRC_DIR/}"
  app="${c%.c}"
  cc $CFLAGS "$LIB_OBJ_DIR"/*.o "$src" $LDFLAGS -o "$APP_DIST_DIR/$app" || exit 1
done
